title: HEHBVEH
description: "Hehbveh is a captivating podcast featuring AI-generated voice content from a diverse array of celebrities. Dive into thought-provoking conversations, immersive storytelling, and insightful commentary, all brought to life by cutting-edge artificial intelligence technology. Join us on a journey where the boundaries between reality and AI blur, offering a unique and engaging listening experience unlike any other."
author: Hehbveh
email: hehbveh@gmail.com
lang: en-us
copyright: "&#xA9; 2024"
logo: /assets/img/omer.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock

theme: jekyll-theme-hacker
