title: HEHBVEH
description: "hehbveh: Adventures through the unknown and the anonymous."
author: Hehbveh
email: hehbveh@gmail.com
lang: en-us
copyright: "&#xA9; 2024"
logo: /assets/img/Logo.jpg
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
