title: HEHBVEH
description: You'll hear me talk about amazing things!
author: Hehbveh
email: hehbveh@gmail.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2024"
logo: /assets/img/logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
